// Generated by gencpp from file navigation/systemparameter.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_SYSTEMPARAMETER_H
#define NAVIGATION_MESSAGE_SYSTEMPARAMETER_H

#include <ros/service_traits.h>


#include <navigation/systemparameterRequest.h>
#include <navigation/systemparameterResponse.h>


namespace navigation
{

struct systemparameter
{

typedef systemparameterRequest Request;
typedef systemparameterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct systemparameter
} // namespace navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation::systemparameter > {
  static const char* value()
  {
    return "684c937ff30737cca1b0e49f2bc137f9";
  }

  static const char* value(const ::navigation::systemparameter&) { return value(); }
};

template<>
struct DataType< ::navigation::systemparameter > {
  static const char* value()
  {
    return "navigation/systemparameter";
  }

  static const char* value(const ::navigation::systemparameter&) { return value(); }
};


// service_traits::MD5Sum< ::navigation::systemparameterRequest> should match 
// service_traits::MD5Sum< ::navigation::systemparameter > 
template<>
struct MD5Sum< ::navigation::systemparameterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::systemparameter >::value();
  }
  static const char* value(const ::navigation::systemparameterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::systemparameterRequest> should match 
// service_traits::DataType< ::navigation::systemparameter > 
template<>
struct DataType< ::navigation::systemparameterRequest>
{
  static const char* value()
  {
    return DataType< ::navigation::systemparameter >::value();
  }
  static const char* value(const ::navigation::systemparameterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation::systemparameterResponse> should match 
// service_traits::MD5Sum< ::navigation::systemparameter > 
template<>
struct MD5Sum< ::navigation::systemparameterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::systemparameter >::value();
  }
  static const char* value(const ::navigation::systemparameterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::systemparameterResponse> should match 
// service_traits::DataType< ::navigation::systemparameter > 
template<>
struct DataType< ::navigation::systemparameterResponse>
{
  static const char* value()
  {
    return DataType< ::navigation::systemparameter >::value();
  }
  static const char* value(const ::navigation::systemparameterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_MESSAGE_SYSTEMPARAMETER_H
