// Generated by gencpp from file navigation/systemparameterRequest.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_SYSTEMPARAMETERREQUEST_H
#define NAVIGATION_MESSAGE_SYSTEMPARAMETERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct systemparameterRequest_
{
  typedef systemparameterRequest_<ContainerAllocator> Type;

  systemparameterRequest_()
    : k1(0.0)
    , k2(0.0)
    , k3(0.0)
    , k4(0.0)  {
    }
  systemparameterRequest_(const ContainerAllocator& _alloc)
    : k1(0.0)
    , k2(0.0)
    , k3(0.0)
    , k4(0.0)  {
    }



   typedef double _k1_type;
  _k1_type k1;

   typedef double _k2_type;
  _k2_type k2;

   typedef double _k3_type;
  _k3_type k3;

   typedef double _k4_type;
  _k4_type k4;




  typedef boost::shared_ptr< ::navigation::systemparameterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::systemparameterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct systemparameterRequest_

typedef ::navigation::systemparameterRequest_<std::allocator<void> > systemparameterRequest;

typedef boost::shared_ptr< ::navigation::systemparameterRequest > systemparameterRequestPtr;
typedef boost::shared_ptr< ::navigation::systemparameterRequest const> systemparameterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::systemparameterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::systemparameterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'navigation': ['/home/pulkit/urc2016/catkin_ws/src/navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navigation::systemparameterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::systemparameterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::systemparameterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::systemparameterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::systemparameterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::systemparameterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::systemparameterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8073fa335b04de6ea2e3d06ae48b2121";
  }

  static const char* value(const ::navigation::systemparameterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8073fa335b04de6eULL;
  static const uint64_t static_value2 = 0xa2e3d06ae48b2121ULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::systemparameterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/systemparameterRequest";
  }

  static const char* value(const ::navigation::systemparameterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::systemparameterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 k1\n\
float64 k2\n\
float64 k3\n\
float64 k4\n\
";
  }

  static const char* value(const ::navigation::systemparameterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::systemparameterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.k1);
      stream.next(m.k2);
      stream.next(m.k3);
      stream.next(m.k4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct systemparameterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::systemparameterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::systemparameterRequest_<ContainerAllocator>& v)
  {
    s << indent << "k1: ";
    Printer<double>::stream(s, indent + "  ", v.k1);
    s << indent << "k2: ";
    Printer<double>::stream(s, indent + "  ", v.k2);
    s << indent << "k3: ";
    Printer<double>::stream(s, indent + "  ", v.k3);
    s << indent << "k4: ";
    Printer<double>::stream(s, indent + "  ", v.k4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_SYSTEMPARAMETERREQUEST_H
